#home_page:
#    pattern: /
#    defaults: { _controller: KyklosSiteBundle:Home:index }

#test_route_js:
#    pattern: /{name}
#    defaults: { _controller: KyklosSiteBundle:Home:testJsRoute }
#    options:
#        expose: true